// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM07QfXE4Rn6wktVFPcfTGa-FbPz4q5cg',
    appId: '1:413896103196:web:69d1e26dbea3cba2bc96d9',
    messagingSenderId: '413896103196',
    projectId: 'chat-app-93638',
    authDomain: 'chat-app-93638.firebaseapp.com',
    storageBucket: 'chat-app-93638.appspot.com',
    measurementId: 'G-H1N1KGT9YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC6V1zSjUhkwNAkaS6cwhnnt82xylPRTw',
    appId: '1:413896103196:android:48ed09f086930305bc96d9',
    messagingSenderId: '413896103196',
    projectId: 'chat-app-93638',
    storageBucket: 'chat-app-93638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYowmSTo3cwMCrtB7EYFJBZkJZBhPRCI',
    appId: '1:413896103196:ios:5cddc75ea2c48c58bc96d9',
    messagingSenderId: '413896103196',
    projectId: 'chat-app-93638',
    storageBucket: 'chat-app-93638.appspot.com',
    iosClientId: '413896103196-9fqv40dsirb5f7qf8l5iel0lvvh9aqs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYowmSTo3cwMCrtB7EYFJBZkJZBhPRCI',
    appId: '1:413896103196:ios:5cddc75ea2c48c58bc96d9',
    messagingSenderId: '413896103196',
    projectId: 'chat-app-93638',
    storageBucket: 'chat-app-93638.appspot.com',
    iosClientId: '413896103196-9fqv40dsirb5f7qf8l5iel0lvvh9aqs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
